# Generated by Django 4.1.3 on 2022-11-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
