# Generated by Django 4.1.3 on 2022-11-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_category_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_amount',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
