# Generated by Django 4.1.3 on 2022-11-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bids_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
