# Generated by Django 4.1.3 on 2022-11-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_bids_listing_alter_bids_bidder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
